Today we will learn different libraries in python

In [ ]:
import numpy as np


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4 5 6 7 8 9]
1
(9,)
9
int64


In [ ]:
arr2=np.array([1.2,6.9,5.366641,56162.5621621])
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

1
(4,)
4
float64


In [ ]:
import numpy as np
arr3=np.array([[1,2],[3,4]])
print(arr3.size)
print(arr3.ndim)
print(arr3.dtype)

4
2
int64


np.arange(starting_value, Ending_Value, step_value)

In [ ]:
np.arange(0,800,40)
np.arange(100,0,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

np.linespace is a function which acts as np.arange function.
syntax:
np.linespace(0,1,5)
output: 0, 0.25, 0.50,0.75,1.0

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
import numpy as np
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
import numpy as np
a= np.array([[7,8,9],[10,11,12]])
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b[1,2])
print(b[1,0])
print(b[1,:])
print(b[:,1])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[1 2 3]
 [4 5 6]]
6
4
[4 5 6]
[2 5]
[[ 8 10 12]
 [14 16 18]]
[[6 6 6]
 [6 6 6]]
[[ 7 16 27]
 [40 55 72]]
[[7.  4.  3. ]
 [2.5 2.2 2. ]]


In [ ]:
np.sqrt([1,4,9])

array([1., 2., 3.])

In [ ]:
np.exp([1,2,3])

array([ 2.71828183,  7.3890561 , 20.08553692])

We also have trigonmetric function s in numerical functions in numerical python

In [ ]:
np.sin([0,np.pi/2,np.pi/3])

array([0.       , 1.       , 0.8660254])

In [ ]:
d=np.array([[1,2],[3,4],[5,6]])
print(d)
print("             ")
print(d.reshape(2,3))
print(d.flatten())

[[1 2]
 [3 4]
 [5 6]]
             
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
